language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - rbx-2
gemfile:
  - gemfiles/ar40.gemfile
  - gemfiles/ar41.gemfile
before_install:
  - sudo apt-get update
  - sudo apt-get install libgeos-dev libproj-dev
